[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-http = "3.3.1"
actix-web = "4.3.1"
config = "0.13.3"
serde = { version = "1", features = ["derive"]}

[dev-dependencies]
actix-rt = "2.8.0"
reqwest = "0.11.16"
tokio = "1.27.0"
